### ISSUE TITLE
Not Working On Lion

### ISSUE THREAD

**Issue by TheKidCoder** [revned/proximity#4]
I am running Lion DP4 and just downloaded Proximity. 

The application will open, however, if I try and open up Preferences.... nothing happens.

**Comment by maxrcho** [comment]
I'm running on Lion 10.7.1 and it works fine. When you open the pref pane, it automatically appears BEHIND all currently visible windows. Try closing open windows, and see if you can replicate the issue?

**Comment by TheKidCoder** [comment]
Works just fine on Lion 10.7.1, must have been a bug with the DP I was on.
